CXX=g++
CXX_FLAGS=-std=c++14 -O3 -march=native -mtune=native -Wall -Wextra -Wshadow

inversions: src/test_inversions.cpp src/inversions.hpp src/test_utilities.hpp
	$(CXX) $(CXX_FLAGS) -o inversions src/test_inversions.cpp
